# Generated by Django 3.1.3 on 2020-11-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('intro', models.CharField(default='', max_length=511, verbose_name='介绍')),
                ('create_date', models.DateField(null=True, verbose_name='成立日期')),
                ('is_not', models.BooleanField(default=False, verbose_name='是否热门')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('good_count', models.IntegerField(default='', verbose_name='好评数')),
                ('bad_count', models.IntegerField(default='', verbose_name='差评数')),
                ('subject', models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, to='vote.subject', verbose_name='所属学科')),
            ],
        ),
    ]
